version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestmart_db
    ports:
      - '5432:5432'